#!/bin/bash

export EDITOR='emacsclient -a ""'
export TERM=xterm-256color
export LANG=en_US.UTF-8

if [ -f "$ZHANGYI_CONFIG_DIR/bashrc/alias.sh" ]; then
    . "$ZHANGYI_CONFIG_DIR/bashrc/alias.sh"
fi

